### ISSUE TITLE
when you run train.py it throws error

### ISSUE THREAD

**Issue by decanbay** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#4]
FileNotFoundError: [Errno 2] No such file or directory: 'BEST_checkpoint_ssd300.pth.tar'

**Comment by sgrvinod** [comment]
Hi, the tutorial is complete now. Please see [this section](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#training) to commence training.

If you want to use an existing checkpoint in any file, which is why you got the error, you can download it as mentioned [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#model-checkpoint).
